title: Quiz with Hidden Answers
show_right_answer: false
questions:
  - question: What is 2 + 2?
    options: ["3", "4", "5", "6"] 
    correct_answer: 1
  - question: What is 3 + 3?
    options: ["5", "6", "7", "8"]
    correct_answer: 1
